---

Join:
  Enabled: true
  message: "&l&6{PLAYER} &f Has joined the server"

Quit:
  Enabled: true
  message: "&l&6{PLAYER} &f Has left the server"

WhitelistedServer:
  Enabled: true
  message: "&l&6This Server is whitelisted right now"

...
